name: server ci

on:
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install dependencies
              run: npm ci

            - name: Generate prisma client
              run: npm run generate

            - name: Build server
              run: npm run build-server

            - name: Lint server
              run: npm run lint-server

            - name: Typecheck server
              run: npm run typecheck-server
